# Generated by Django 2.0.2 on 2019-12-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die', models.CharField(choices=[('D4', '4'), ('D6', '6'), ('D8', '8'), ('D10', '10'), ('D12', '12'), ('D20', '20')], default='D4', max_length=20)),
                ('number_of_die', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='die',
        ),
        migrations.AddField(
            model_name='weapon',
            name='die',
            field=models.ManyToManyField(to='equipment.Die'),
        ),
    ]
