# Generated by Django 2.0.2 on 2020-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classpick', models.CharField(choices=[('Rogue', 'Rogue')], default='Rogue', max_length=20)),
                ('die', models.ManyToManyField(to='equipment.Die')),
            ],
        ),
    ]
