# Generated by Django 2.0.2 on 2019-10-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alignment', models.CharField(choices=[('NPC', 'NPC'), ('Player', 'Player')], default='Player', max_length=32)),
                ('max_hp', models.IntegerField()),
            ],
        ),
    ]
