# Generated by Django 2.0.2 on 2019-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('party', '0003_auto_20191110_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='weapons',
            field=models.ManyToManyField(to='equipment.Weapon'),
        ),
    ]
