# Generated by Django 2.0.2 on 2019-12-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_base_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='equipment.Weapon'),
        ),
    ]
