# Generated by Django 2.0.2 on 2019-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='player_type',
            field=models.CharField(choices=[('Adventurer', 'Adventurer'), ('DM', 'DM')], default='Adventurer', max_length=20),
        ),
    ]
