# Generated by Django 2.0.2 on 2019-11-10 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0002_auto_20191029_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatmember',
            name='current_hp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
